version: "3"

services:

  api:
    build: .
    container_name: pneumonia_api
    ports:
      - "8000:8000"
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000

  ui:
    build: .
    container_name: pneumonia_ui
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://api:8000
    command: streamlit run app_streamlit.py --server.port=8501 --server.address=0.0.0.0